package main

import (
	"bytes"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

var methods = map[string]bool{"get": true, "post": true, "put": true, "patch": true, "delete": true}
var coreGenerationRank = map[string]int{"legacy": 0, "v0": 1, "v1": 2, "v2": 3, "v3": 4}

type document struct {
	Info struct {
		Generation string `json:"x-esper-generation"`
	} `json:"info"`
	Paths      map[string]map[string]operation `json:"paths"`
	Components struct {
		Schemas map[string]schema `json:"schemas"`
	} `json:"components"`
}

type operation struct {
	Parameters []parameter `json:"parameters"`
	Body       struct {
		Content map[string]requestMedia `json:"content"`
	} `json:"requestBody"`
	Noun        string `json:"x-esper-noun"`
	Verb        string `json:"x-esper-verb"`
	Pagination  string `json:"x-esper-pagination"`
	Destructive bool   `json:"x-esper-destructive"`
	ScopeParent string `json:"x-esper-scope-parent"`
}

type parameter struct {
	Name     string `json:"name"`
	In       string `json:"in"`
	Required bool   `json:"required"`
	Schema   schema `json:"schema"`
}

type requestMedia struct {
	Schema schema `json:"schema"`
}
type schema struct {
	Ref        string            `json:"$ref"`
	Type       any               `json:"type"`
	Format     string            `json:"format"`
	Enum       []any             `json:"enum"`
	Properties map[string]schema `json:"properties"`
	Required   []string          `json:"required"`
}

type generatedOperation struct {
	Generation  string
	Command     []string
	Method      string
	Path        string
	Noun        string
	Verb        string
	Pagination  string
	Destructive bool
	ScopeParent string
	Parameters  []generatedParameter
	Body        *generatedBody
}
type generatedParameter struct {
	Name, In, Type  string
	Required, Scope bool
	Enum            []string
}
type generatedBody struct {
	MediaType  string
	Properties []generatedProperty
}
type generatedProperty struct {
	Name, Type, Format string
	Required, File     bool
	Enum               []string
}

func main() {
	specDir := flag.String("spec-dir", "spec/openapi", "directory containing resolved OpenAPI files")
	output := flag.String("output", "internal/cmd/generated/zz_generated_commands.go", "generated Go source path")
	flag.Parse()
	operations, err := load(*specDir)
	if err != nil {
		fatal(err)
	}
	assignCommands(operations)
	sort.Slice(operations, func(i, j int) bool {
		left, right := strings.Join(operations[i].Command, "\x00"), strings.Join(operations[j].Command, "\x00")
		if left != right {
			return left < right
		}
		if operations[i].ScopeParent != operations[j].ScopeParent {
			return operations[i].ScopeParent < operations[j].ScopeParent
		}
		if operations[i].Path != operations[j].Path {
			return operations[i].Path < operations[j].Path
		}
		return operations[i].Method < operations[j].Method
	})
	data, err := json.Marshal(operations)
	if err != nil {
		fatal(err)
	}
	var source bytes.Buffer
	source.WriteString("// Code generated by tools/codegen; DO NOT EDIT.\n\npackage generated\n\n")
	source.WriteString("var generatedOperationsJSON = []byte(`")
	source.Write(data)
	source.WriteString("`)\n")
	if err := os.MkdirAll(filepath.Dir(*output), 0o755); err != nil {
		fatal(err)
	}
	if err := os.WriteFile(*output, source.Bytes(), 0o644); err != nil {
		fatal(err)
	}
}

func load(directory string) ([]generatedOperation, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return nil, err
	}
	var result []generatedOperation
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".yaml") {
			continue
		}
		data, err := os.ReadFile(filepath.Join(directory, entry.Name()))
		if err != nil {
			return nil, err
		}
		var spec document
		if err := json.Unmarshal(data, &spec); err != nil {
			return nil, fmt.Errorf("decode %s: %w", entry.Name(), err)
		}
		for apiPath, item := range spec.Paths {
			for method, operation := range item {
				if !methods[method] {
					continue
				}
				generated := generatedOperation{Generation: spec.Info.Generation, Method: strings.ToUpper(method), Path: apiPath, Noun: operation.Noun, Verb: operation.Verb, Pagination: operation.Pagination, Destructive: operation.Destructive, ScopeParent: operation.ScopeParent}
				for _, parameter := range operation.Parameters {
					resolved := resolve(parameter.Schema, spec.Components.Schemas)
					generated.Parameters = append(generated.Parameters, generatedParameter{Name: parameter.Name, In: parameter.In, Type: scalarType(resolved), Required: parameter.Required, Scope: operation.ScopeParent != "" && parameter.In == "path", Enum: stringEnum(resolved.Enum)})
				}
				if len(operation.Body.Content) > 0 {
					generated.Body = extractBody(operation.Body.Content, spec.Components.Schemas)
				}
				result = append(result, generated)
			}
		}
	}
	return result, nil
}

func resolve(value schema, schemas map[string]schema) schema {
	if !strings.HasPrefix(value.Ref, "#/components/schemas/") {
		return value
	}
	name := strings.TrimPrefix(value.Ref, "#/components/schemas/")
	resolved, ok := schemas[name]
	if !ok {
		return value
	}
	return resolve(resolved, schemas)
}

func extractBody(content map[string]requestMedia, schemas map[string]schema) *generatedBody {
	mediaType := ""
	if _, ok := content["application/json"]; ok {
		mediaType = "application/json"
	} else if _, ok := content["multipart/form-data"]; ok {
		mediaType = "multipart/form-data"
	} else {
		return nil
	}
	value := resolve(content[mediaType].Schema, schemas)
	required := map[string]bool{}
	for _, name := range value.Required {
		required[name] = true
	}
	body := &generatedBody{MediaType: mediaType}
	for _, name := range sortedKeys(value.Properties) {
		property := resolve(value.Properties[name], schemas)
		typeName := scalarType(property)
		file := mediaType == "multipart/form-data" && typeName == "string" && property.Format == "binary"
		if !file && !isScalar(typeName) {
			continue
		}
		body.Properties = append(body.Properties, generatedProperty{Name: name, Type: typeName, Format: property.Format, Required: required[name], File: file, Enum: stringEnum(property.Enum)})
	}
	return body
}

func assignCommands(operations []generatedOperation) {
	type candidate struct{ index, rank int }
	groups := map[string][]candidate{}
	for index := range operations {
		operation := &operations[index]
		key := operation.Noun + "\x00" + operation.Verb
		rank, core := coreGenerationRank[operation.Generation]
		if !core {
			rank = 100
		}
		groups[key] = append(groups[key], candidate{index: index, rank: rank})
	}
	for _, candidates := range groups {
		maxRank := -1
		for _, candidate := range candidates {
			if candidate.rank > maxRank {
				maxRank = candidate.rank
			}
		}
		for _, candidate := range candidates {
			operation := &operations[candidate.index]
			if _, core := coreGenerationRank[operation.Generation]; core && candidate.rank < maxRank {
				operation.Command = []string{"api", operation.Generation, operation.Noun, operation.Verb}
			} else {
				operation.Command = []string{operation.Noun, operation.Verb}
			}
		}
	}
}

func scalarType(value schema) string {
	switch typed := value.Type.(type) {
	case string:
		return typed
	case []any:
		for _, item := range typed {
			if text, ok := item.(string); ok && text != "null" {
				return text
			}
		}
	}
	return "object"
}
func isScalar(kind string) bool {
	return kind == "string" || kind == "number" || kind == "integer" || kind == "boolean"
}
func stringEnum(values []any) []string {
	result := make([]string, 0, len(values))
	for _, value := range values {
		result = append(result, fmt.Sprint(value))
	}
	return result
}
func sortedKeys(values map[string]schema) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}
	sort.Strings(keys)
	return keys
}
func fatal(err error) { fmt.Fprintln(os.Stderr, "error:", err); os.Exit(1) }
